### ISSUE TITLE
Running unit tests

### ISSUE THREAD

**Issue by gunthercox** [torre76/django-googledrive-storage#13]
Hi, I was wondering if I could get instructions for running the unit tests for this module. Typically with django projects there is a `manage.py` file that allows the tests to be run. Is there a different test setup that is being used here?

**Comment by torre76** [comment]
Hi @gunthercox,

when I wrote this module I was a python newbie and I didn't know much about python and Django.
This project was essentially a bed test to learn python, so a lot of concept where unknown to me.

I planned to do real unit testing and, moreover, I would like to use *Travis* to do cross version unit testing but, unfortunately, I am committed to other projects and I manage this one in the spare time.

Feel free to implement unit testing on it, I will surely merge them and use Travis to execute them.

**Comment by torre76** [comment]
Hi @gunthercox, this night I've setup Travis CI integration with the project that runs also Django tests in a custom, but working, manner.

I had ported all your changes and now the project is also Python 3 compatible.
Regards

**Comment by gunthercox** [comment]
@torre76 Awesome, great to hear!
