### ISSUE TITLE
Is _service_email variable used?

### ISSUE THREAD

**Issue by gunthercox** [torre76/django-googledrive-storage#17]
In `storage.py` There is a variable (`self._service_email`) and I don't believe it is used anywhere since the service email is loaded from the JSON credential file.

**Comment by torre76** [comment]
Hi @gunthercox,

you are right, the parameter is no longer used.
Since I will release 1.3.0, I removed the service email (it is a backward incompatibility, but not so hard to fix).

Thank you!

**Comment by torre76** [comment]
Forgot to remove the request of `SERVICE_EMAIL` from `GoogleDriveStorageConf`.

Need to release 1.3.1
