### ISSUE TITLE
Non-service-account usage.

### ISSUE THREAD

**Issue by dmwyatt** [torre76/django-googledrive-storage#19]
I was thinking about submitting a pull request for usage with a regular client_secrets.json style of Drive account so it can store files in a specific users Drive.

Is there a particular reason this has not been implemented other than no one has needed it before now?

Just wondering if there were any roadblocks I'm not thinking about off-hand.

**Comment by torre76** [comment]
Hi @dmwyatt,

sorry for being late on reply to you.

Essentially, when I started this project, there was no way to access a personal Google Drive through Google API. 
The key you could obtain was related only to a Google Drive attached to a project (not a person). In fact Google didn't provided any interface like Google Drive Web to manage Google Drive Project Disks.

After your request, I dug into [Google Developer Console for Google Drive](https://console.developers.google.com/start/api?id=drive) and I found that now it is possible to use a personal drive.

Saying that, I do not see any problem at all to integrate this project with a personal storage. I encourage you to submit your pull request ;)
