### ISSUE TITLE
New permissions setup causes a ValueError on import

### ISSUE THREAD

**Issue by anka-sirota** [torre76/django-googledrive-storage#21]
the `_ANYONE_CAN_READ_PERMISSION_` definition causes it, it seems

```
>>> import gdstorage.storage
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/anna/envs/finance/src/django-googledrive-storage/gdstorage/storage.py", line 154, in <module>
    GoogleDrivePermissionType.ANYONE
  File "/home/anna/envs/finance/src/django-googledrive-storage/gdstorage/storage.py", line 141, in __init__
    raise ValueError("Role should be a GoogleDrivePermissionRole instance")
ValueError: Role should be a GoogleDrivePermissionRole instance
```
maybe that's an indication that the whole enummed object setup is a bit overly complicated for the task it's solving =]

**Comment by torre76** [comment]
Which version of Python are you using @anka-sirota?

**Comment by anka-sirota** [comment]
Python 2.7.12

**Comment by torre76** [comment]
I am trying to reproduce your error locally, but It is not happening on **Python 2.7**.
The error stated by stack trace implies that the code is misplacing _Role_ and _Type_ (which, if you look at the code is impossible).

I also take a look at [auto build on Travis](https://travis-ci.org/torre76/django-googledrive-storage/jobs/179110634) and it is working as expected.

Are you using a separate virtual environment for your project?
Have you tried to remove and install again the package?

**Comment by anka-sirota** [comment]
turns out I have another `enum` installed in this virtualenv, my bad.

**Comment by torre76** [comment]
At least the code is working as expected ;)

Thank you!
