### ISSUE TITLE
MemoryError on large files

### ISSUE THREAD

**Issue by jamesgao** [torre76/django-googledrive-storage#25]
In [line 310 in storage.py](https://github.com/torre76/django-googledrive-storage/blob/60aa430c6a891d2c48b8bc2079be51193098b348/gdstorage/storage.py#L310), there's a `content.file.read()` operation. If the file to be uploaded is very large, this step fails. Is there a way to avoid the `content.file.read()` step?

**Comment by torre76** [comment]
Hi @jamesgao,

I noticed you have fixed this issue on your cloned repo.
How about to issue a pull request?

Regards

**Comment by torre76** [comment]
Fixed the huge file uploading.

I cannot figure how to fix downloading, because the File class used by django storage requires a complete stream from which to load from.
