### ISSUE TITLE
Browse uploaded files

### ISSUE THREAD

**Issue by sir-ion** [torre76/django-googledrive-storage#31]
Hi,
I've being trying to write myself a storage service like this for files uploaded by users on my site, though I've never managed to achieve the following two functionalities and still I can't find out if:

1. Google Drive allows to navigate through the files uploaded and move/delete/rename/etc... them. I've found out [this example](https://developers.google.com/picker/docs/) by Google, but it seems to be able to show only the files inside a user's GDrive, not those uploaded inside the folder of a Server to Server implementation.

2. When I want to retrieve and show an image (that has been successfully uploaded through my site to Google Drive) on a page I use something like `<img src="{{ my_model_instance.image_file.url }}" />` but the browser do not display any image. Actually if a visit the url `my_model_instance.image_file.url` (which is something like `https://drive.google.com/file/d/0B2pLMZGasddCTjZ6UmJ1UVFOSjg/view`) I do not see a plain image, but a whole 'visualizer' (see the attachment) which has much more HTML code other than the a simple image.

Any hint or advice on these issues will be highly appreciated, thank you.

![gdrive_file](https://user-images.githubusercontent.com/16246280/28488203-52239c14-6ea5-11e7-8b4c-3fa47608336a.jpg)

**Comment by torre76** [comment]
Hi @sir-ion,

1. If you mean that you want to use Google Drive User Interface to see and update an application Drive, I am afraid this is not possible. If you have Google Suite (a paid Gmail account with custom domain) you could use an User Google Drive with API (and thus you can also use Google Standard Interface) using OAuth2 as stated [here](https://developers.google.com/drive/v3/web/about-auth).
2. As I can understand, you do not fully understand how a [Django Storage](https://docs.djangoproject.com/en/1.11/howto/custom-file-storage/) works, neither how[ Google Drive](https://developers.google.com/drive/v3/web/manage-downloads) works. I suggest you to look at my implementation, in particular [here](https://github.com/torre76/django-googledrive-storage/blob/master/gdstorage/storage.py#L303).

Please, do not open issues on project when there is not a problem with the project itself. 

You could contact me through github or [any other way](https://keybase.io/torre76) you prefer but this place is only for problems related to this project, it is not a forum for asking programming hints.

Regards

**Comment by sir-ion** [comment]
Ciao, sono sir-ion (uso l’italiano per semplificare le cose).

Anzitutto, grazie per la risposta!

Ora che hai spostato l’issue tra quelle chiuse mi sono accorto che la mia
seconda domanda corrisponde a questa:
https://github.com/torre76/django-googledrive-storage/issues/30
anche se questo workaround mi è troppo scomodo.

Non so se può interessarti ma al momento ho risolto usando il progetto
‘django-storages’ con Dropbox come servizio. Questa soluzione mi permette
di usare direttamente  <img src="{{ my_model_instance.image_file.url }}" />
 all’interno del template django e tutto funziona. Questo potrebbe essere
molto comodo per persone che come me vogliono usare un servizio di file
hosting come storage per un sito web. Volevo solo fartelo sapere nel caso
in futuro volessi implementare in qualche modo questa possibilità.

Grazie ancora,
sir-ion.


P.S.: scusa se ho usato una issue di github per questo genere di domanda
(sapevo che poteva essere un abuso), ma per altri progetti mi è capitato il
contrario con domande analoghe, ovvero di contattare lo sviluppatore
direttamente e sentirmi dire di aprire una issue...

P.P.S.: sulla tua pagina personale di github non compare il tuo indirizzo
email (o forse sono solo io che non lo trovo... )

**Comment by torre76** [comment]
Ciao @sir-ion,

non ti preoccupare per dove mi contatti, io preferisco l'email per comodità, ma va bene anche qui.

Capisco cosa ti serve e perché ti serve, ma di fatto quello che mi stai chiedendo è di modificare il metodo che recupera l'URL utilizzando il workaround id #30. 

Sono abbastanza restio a farlo per un problema di performance. Google Drive con le API ti da l'URL del loro _player_ e capisco che sia fastidioso, ma se Google non mi passa il contenuto già pronto per essere visualizzato significa che il progetto deve farlo da solo e questo è potenzialmente pericoloso. 
Immagina che tu visualizzi una lista di 10 immagini che occupano (sempre parlando per ipotesi), 1mb l'una, significa che io devo caricare nella RAM del server 10mb di immagini per mostrare una schermata... Se il server è trafficato capisci che questo è un problema non da poco (potrebbe piantarsi tutto).

Non so come Dropbox gestisca la cosa, molto probabilmente da già l'URL funzionante e immagino che sia anche quello il motivo per cui quel bel progetto non ha (ancora) incluso Google Drive.

Detto questo, puoi sempre fare un fork del progetto e gestirti la cosa come vuoi.

A presto!
