### ISSUE TITLE
Broken pipe

### ISSUE THREAD

**Issue by guy881** [torre76/django-googledrive-storage#33]
Hey, thank you for your package, it is very useful. However I get two exceptions which looks similar, those are raised from time to time, not always. Is there any way it can be handled?
I think I should say, that instance is running inside docker container

Traceback (sorry for image, but it lost formatting on paste):
![image](https://user-images.githubusercontent.com/10159285/45085653-7fae1980-b101-11e8-9cc3-9f4ee5fe4498.png)
![image](https://user-images.githubusercontent.com/10159285/45085705-a9ffd700-b101-11e8-9938-d593bb10755b.png)

**Comment by torre76** [comment]
Hi @guy881,

sorry for being late ;)

Looking at your stack trace it is clear that something went wrong on network communication between your *dockerized* app and *Google*.  
The fact that this errors occurs seldomly is a confirmation about that.

This package could no nothing about that, a network error should not occur but it is always possible.
What you have to do is to catch the exception and handle it (either retrying or showing a message that explains what happened).

I suggest you to contact your system administrator and states which problem you have, maybe it can solve it for you.
