### ISSUE TITLE
Problems and ideas to discuss

### ISSUE THREAD

**Issue by HacKanCuBa** [torre76/django-googledrive-storage#34]
Hello! Sorry to make one huge issue but my idea is to discuss each point I will present and then create individual issues.

I used this module in a recent project a found several problems which I would like help solving. I used python 3.6, django 2.1 and rest framework 3.9

Here's the list of problems I found:

* the api in use is v2, it should be migrated to v3 (maybe this solves several problems?).
* directory creation is not working; instead, the "directory" (upload_to param) is appended to the file name.
* if the upload_to param doesn't contains a dash (-), it crashes.
* if the upload_to param doesn't contains a backlash (/), it crashes.
* if the upload_to param is an empty string, it crashes.
* if the file name to store contains dashes (-), it crashes.
* sometimes, it will crash for no apparent  reason: I tried with the same file several times, and about 10% of the time it would crash.
* changing a permission or username affects the model, triggering a new migration (there's no need to apply it, but every change will trigger a migration!)

I can give you access to the project where I used this module, it's quite small and maybe useful for testing purposes.

I believe this project can be very useful, especially given that's the only one to give storage to Google drive. I would like to expand it a bit to have also retrieval and query capabilities.

How would you like to proceed?

Cheers!

**Comment by AndryTverdyi** [comment]
`    file_data['downloadUrl'])
TypeError: 'NoneType' object is not subscriptable`

I have this problem. Where I should to get "downloadUrl" if I run upload without FileField() ?

**Comment by HacKanCuBa** [comment]
> ` file_data['downloadUrl']) TypeError: 'NoneType' object is not subscriptable`
> 
> I have this problem. Where I should to get "downloadUrl" if I run upload without FileField() ?

I have no idea honestly.

**Comment by torre76** [comment]
Hi @HacKanCuBa,

sorry to reply so late but I am very busy lately and I do not have so much time to spend on this project anymore.

Please feel free to create a PR (maybe more than one) to address the problem you found and, I will glad to review and merge them.

**Comment by torre76** [comment]
@AndryTverdyi The problem you describe deserves a separate issue.

Please create a new one, also posting the code have write that causes that error and also:

* Python version
* Django Version

**Comment by HacKanCuBa** [comment]
> Hi @HacKanCuBa,
> 
> sorry to reply so late but I am very busy lately and I do not have so much time to spend on this project anymore.
> 
> Please feel free to create a PR (maybe more than one) to address the problem you found and, I will glad to review and merge them.

Don't worry, we are all in the same place :D

**Comment by torre76** [comment]
I close these for inactivities.
