### ISSUE TITLE
Support for Google Drive API v3

### ISSUE THREAD

**Issue by ugaemi** [torre76/django-googledrive-storage#35]
Thanks to you, I've made it easy to connect Django and Google drive.
But there were some changes that needed to be made to work with Google Drive api v3 😊

If there is an error in the `test_check_root_file_exists` test, please check if there is the file.

**Comment by torre76** [comment]
Hi @ugaemi 

thank you for your support.
Sorry for being so late for this MR but I was very busy in the last few months.

Now I have merged your code and released the [new version on Pypi](https://pypi.org/project/django-googledrive-storage/).

Thank you again!
