### ISSUE TITLE
Support for enviroment vars

### ISSUE THREAD

**Issue by rnovec** [torre76/django-googledrive-storage#38]
This is a powerful tool to connect Django and Google Drive.
But there are a few changes that need to be made to make it work better with the Google Drive API.

Support for passing `key.json` data as environment variables individually, this feature would make it easy to deploy into a public repository (i.e. **Heroku**).

Without this feature, `key.json` is not secure in public repositories.

**Comment by torre76** [comment]
Hi @rnovec 

Thank you for your suggest.  
Honestly this feature is so specific to the _Heroku deploy system_ that is not a blocker for this project.

But, If you provide a pull request with the changes required for your idea, I will gladly rewiew it and possibly merge into the project.

Regards

**Comment by mca10** [comment]
@rnovec There’s a PR up now for addressing this ^

In case you’re still stuck with this, you can do the following in the meantime:

In Heroku, you can set two config vars: one for the location of your `key.json` (you could simply name it `GOOGLE_DRIVE_STORAGE_JSON_KEY_FILE` for consistency’s sake, and another for the actual contents... something like `GOOGLE_DRIVE_JSON_KEY` or whatever)

You then set up a pre_compile hook (create a `bin/pre_compile` file in your project), with this content:
```sh
#!/usr/bin/env bash
set -eo pipefail
echo "-----> Creating google drive key file"
echo $GOOGLE_DRIVE_JSON_KEY > $GOOGLE_DRIVE_STORAGE_JSON_KEY_FILE
```

That will get executed on deploy and you’ll get your json key file in the desired location, then in the `settings.py` file you can just do...
```python
GOOGLE_DRIVE_STORAGE_JSON_KEY_FILE = os.path.join(
    BASE_DIR,
    os.environ.get('GOOGLE_DRIVE_STORAGE_JSON_KEY_FILE'),
)
```

**Comment by rnovec** [comment]
@mca10 I'm following your PR's, this is a great feature. Thanks for advice

**Comment by rnovec** [comment]
#41 @torre76 We'll waiting for revision and merge. There are others interestaing features that @mca10 has been working

**Comment by torre76** [comment]
Hi @mca10, hi @rnovec 

Release `1.5.0`has been published on PyPi.

Thank you for your support!
