### ISSUE TITLE
Full file retrieval

### ISSUE THREAD

**Issue by thismatters** [torre76/django-googledrive-storage#43]
Hello, 

Thank you for this package, we have been using it since 1.3.5 and it has been working great. However, the latest version (1.5.1) seems to have divergent behavior from 1.3.5. Namely the content of the file, when downloaded, appears to be google view of the file. As a specific example when I try to download a previously uploaded file I get the following (truncated):

```html
<!DOCTYPE html>
<html lang="en">
  <head>
  <meta charset="utf-8">
  <meta content="width=300, initial-scale=1" name="viewport">
  <meta name="description" content="Google Drive is a free way to keep your files backed up and easy to reach from any phone, tablet, or computer. Start with 15GB of Google storage – free.">
  <meta name="google-site-verification" content="LrdTUW9psUAMbh4Ia074-BPEVmcpBxF6Gwf0MSgQXZs">
  <title>Meet Google Drive – One place for all your files</title>
  <style>
...
```

In my `views.py` I'm using the following to provide the file for download to users:
```python 
FileResponse(instance.file, as_attachment=True)
```
This works as expected when using 1.3.5.

**Comment by thismatters** [comment]
According to the [Drive API docs](https://developers.google.com/drive/api/v3/manage-downloads?hl=id#viewing_files_in_a_browser) `webContentLink` is for viewing the file with a browser. The recommended means for downloading the file is using a `MediaIoBaseDownload` object.

**Comment by torre76** [comment]
Hi @thismatters,

sorry for being so late on accepting your PR, but I have been busy.

I created an uploaded [version 1.5.2](https://pypi.org/project/django-googledrive-storage/) on PyPi.

Thank you so much for your fix.
