### ISSUE TITLE
where to place the environment variable

### ISSUE THREAD

**Issue by shikhalakra22** [torre76/django-googledrive-storage#47]
As mentioned in docs that - place the contents of your json private key file into an environment variable named GOOGLE_DRIVE_STORAGE_JSON_KEY_FILE_CONTENTS. 
Do i need to create a file name GOOGLE_DRIVE_STORAGE_JSON_KEY_FILE_CONTENTS and place the json key there?
i am confused about what environment variable. kindly help me with this issue
thanks

**Comment by torre76** [comment]
Hi @shikhalakra22,

you should study what an [environment variable](https://en.wikipedia.org/wiki/Environment_variable) is.

Regards
