### ISSUE TITLE
django 1.7 migration 

### ISSUE THREAD

**Issue by jixtes** [torre76/django-googledrive-storage#5]
Cannot serialize: <gdstorage.storage.GoogleDriveStorage object at 0x7ff386b87cd0>
There are some values Django cannot serialize into migration files.

**Comment by jixtes** [comment]
Hi torre76

When I add the [deconstructable](https://www.google.com.et/url?sa=t&rct=j&q=&esrc=s&source=web&cd=1&cad=rja&uact=8&ved=0CBsQFjAA&url=https%3A%2F%2Fdocs.djangoproject.com%2Fen%2F1.7%2Ftopics%2Fmigrations%2F&ei=67y3VLfPBcTm7gaa54CwCg&usg=AFQjCNG9KBpB6A7EjEqbMYyRaPHfNzMwXQ&sig2=tiJ_b5pqBXRoy-kmSs1JwQ&bvm=bv.83640239,d.ZGU) decorator, it worked. I think the problem appears for the 1.7 django version.

**Comment by torre76** [comment]
Hi @jixtes,

I have committed ce643a8e1d4fd89edbbb4739dd822d30fd5aa571, which hopefully handles Django 1.7 migrations.

Could you build a patch for your project and remove the decorator?
If it works, I will release a new version with the problem solved.
Thank you in advance.

**Comment by torre76** [comment]
Committed patch to Pypi
