### ISSUE TITLE
Using multiple gdstorage in single webapp

### ISSUE THREAD

**Issue by krishna-vasudev** [torre76/django-googledrive-storage#52]
It's evident that we can use drive storage in our django projects. But  just curious is there a way to use multiple gdstorage in a single project.

**Comment by torre76** [comment]
Hi @krishna-vasudev,

It is not clear why there should be multiple `gdstorage` on a single Django project.
`gdstorage` is a concrete implementation for a `Storage` class and, for Django, is only a place where save data.

If you intend that you want to use multiple accounts to store data to bypass the 15GB limit, well `gdstorage` can't do that.

There are multiple problems on handling this kind of behavior (in which account `gdstorage` should save data?) which I am not interested to solve.

So, this project will always deal with a single account on Google.
If you are interested on expanding Google Drive, you should use a business paid account which can have virtually infinite space.
